
imports:
  - path: ./gcs_bucket.py
    name: gcs_bucket.py
    

resources:
  - name: cn-automte
    type: gcs_bucket.py
    properties:
      name: cn-automte
      Environment: dev
      location: us-east1
      versioning:
        enabled: False
    

